// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6iscPjgAS_FRfOFQ9049mWDh_RcruAE',
    appId: '1:762970879166:web:d6c62fae0f44e5fdbf5aef',
    messagingSenderId: '762970879166',
    projectId: 'medimind-2b1b0',
    authDomain: 'medimind-2b1b0.firebaseapp.com',
    storageBucket: 'medimind-2b1b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7jK1HRZ6e5KsFntqcvgBWsimiaJGiJ8I',
    appId: '1:762970879166:android:ee14856a9be99a54bf5aef',
    messagingSenderId: '762970879166',
    projectId: 'medimind-2b1b0',
    storageBucket: 'medimind-2b1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxI8H2G-KDfh1iSXUpQ-kvZ4Njq5tLxk',
    appId: '1:762970879166:ios:7bd4873f1f906c83bf5aef',
    messagingSenderId: '762970879166',
    projectId: 'medimind-2b1b0',
    storageBucket: 'medimind-2b1b0.appspot.com',
    androidClientId: '762970879166-01ots8jf0h481o8eo8c7orscdnva1o98.apps.googleusercontent.com',
    iosClientId: '762970879166-eun2np3lbek8nh0rcap2n409ocre91a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.medimindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxI8H2G-KDfh1iSXUpQ-kvZ4Njq5tLxk',
    appId: '1:762970879166:ios:631d9f60eb06c323bf5aef',
    messagingSenderId: '762970879166',
    projectId: 'medimind-2b1b0',
    storageBucket: 'medimind-2b1b0.appspot.com',
    androidClientId: '762970879166-01ots8jf0h481o8eo8c7orscdnva1o98.apps.googleusercontent.com',
    iosClientId: '762970879166-6kg58jrme76oh80vsfgjeibg1lg7cuba.apps.googleusercontent.com',
    iosBundleId: 'com.example.medimindApp.RunnerTests',
  );
}
